### ISSUE TITLE
Code linter

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/PkgDev.jl#118]
Hello,

PkgDev provides some default configuration files for project management such as:
- running unit tests
- running code coverage
- continuous integration (Travis, AppVeyor ...)

Maybe code linter should be add to default project generation as it may be a good practice also.

Kind regards

Pinging @tonyhffong @TotalVerb from https://github.com/tonyhffong/Lint.jl
but maybe there is also some other code linters

**Comment by ararslan** [comment]
It would be pretty sweet to be able to do `PkgDev.lint("SomePackage")`.

**Comment by tkelman** [comment]
better than `Lint.linpkg("SomePackage")` ?

**Comment by ararslan** [comment]
Nope.

**Comment by scls19fr** [comment]
I think it will be better to do `PkgDev.lint("SomePackage")` because `PkgDev` will use a default linter (maybe Lint.jl by default) but it could change in the future

**Comment by scls19fr** [comment]
or `Pkg.lint("SomePackage")`

but

`Pkg.test("DukascopyTicksReader"; coverage=true, lint=true)`

could be an other idea

**Comment by ararslan** [comment]
I think the best solution here would just be to make Lint.jl more obvious. I'd venture a guess that not that many package authors make use of it in their development but it should be encouraged to do so.

**Comment by TotalVerb** [comment]
Lint also needs to be updated for 0.6 and 0.7 syntax changes, which I'm in the middle of right now. Over the following weeks I should have more time to push some changes through.

**Comment by scls19fr** [comment]
I noticed that some people use Lint in `runtests.jl`
So a `test/REQUIRE` file with Lint would be required
and 

```
using Lint

@test isempty(lintpkg("Pushover"))
```

can be add to `runtests.jl`

I don't really know what is the best approach.

My opinion is that Linter should be run after unit tests.

**Comment by scls19fr** [comment]
Should we have a `runtests.jl` like

```julia
using MyPkg
using Base.Test
using Lint

@testset "MyPkg" begin
    @testset "tests" begin
        # write your own tests here
        @test 1 == 1
    end

    @testset "lint" begin
        @test isempty(lintpkg("MyPkg"))
    end
end
```

?

**Comment by ararslan** [comment]
People who want to test the results of a linter pass could just use something like this on Travis:
```yaml
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Something"); Pkg.test("Something"; coverage=true)';
  - julia -e 'Pkg.add("Lint"); using Lint, Base.Test; @test isempty(lintpkg("Something"))'
after_success:
  - julia -e 'cd(Pkg.dir("Something")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  - julia -e 'cd(Pkg.dir("Something")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
```
Otherwise adding a `testset` manually as you've shown is a good idea. Linting shouldn't be required though.
